### ISSUE TITLE
converted FLIR jpeg images result in 0 Byte files

### ISSUE THREAD

**Issue by RomyWichmann** [gtatters/ThermImageJ#1] opened 2020-02-20 22:52 UTC
**Describe the bug**
While running ConvertFLIRJPG function with FLIR jpgs (even the sample files) I encounter 2 different problems
1) I get a Macro Error 
![MacroError](https://user-images.githubusercontent.com/61289762/74973552-789fc780-53d8-11ea-9090-561368219683.png)

If i then restart image J, the script runs fine as indicated by the log
![log](https://user-images.githubusercontent.com/61289762/74974005-5490b600-53d9-11ea-8413-11cba8d6a892.png)

but the resulting image in the coverted folder has 0 byte
![0 byte](https://user-images.githubusercontent.com/61289762/74974396-05975080-53da-11ea-938d-86b8b7a5f672.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by gtatters** [comment] 2020-02-20 23:31
Aha, I see. indeed, I'll need to fix that.  I rarely use the single convert jpg option, I simply have been using the Import-FLIR-JPG function for most of my applications.  I can reproduce that error on my system, so it is a bug.  I'll look into fixing it and update here.  Meanwhile, please see if the Import function works on your computer, as it would verify most things are properly installed.

If you need one file converted, the function to convert the whole folder of jpgs will work also on one file.  It will look a little messy but it tries every jpg and attempts to extract the raw thermal data.

**Comment by gtatters** [comment] 2020-02-21 00:00
yes, it's officially my first bug (at least that i've shared).  I'll upload a fix shortly, having found where the issue was.  Invariably it comes down to writing the path information accurately.

**Comment by gtatters** [comment] 2020-02-21 00:08
Hopefully it is fixed now in v2.2 (https://github.com/gtatters/ThermImageJ/releases/tag/v2.2)

The easiest way to update is to simply download this text file and copy into your ImageJ/Macros/toolsets folder: 

https://github.com/gtatters/ThermImageJ/blob/master/toolsets/ThermImageJ.ijm

Please let me know if that fixes it for you.

**Comment by RomyWichmann** [comment] 2020-02-21 16:50
Hi, it definitely fixed the issue. The sample images work great now - when i use the import function. The SampleJPG is still not working when i use the convert function though. 
 
Unfortunately, my own images, taken with a FLIR TG267, still don't work. 
This is the error I get when running the import function:
![png issue](https://user-images.githubusercontent.com/61289762/75053405-143b4180-5486-11ea-8717-346911dd6997.png)

This is the error I still get when running the Convert function:
![convert error](https://user-images.githubusercontent.com/61289762/75053827-c6730900-5486-11ea-8ac0-ad9ade3364d4.png)

This might be a camera problem though?

thanks

**Comment by gtatters** [comment] 2020-02-21 16:58
Could you try running the function called "Flir Calibration Values Tool" on your image and on the sample image?  You will likely get a weird error if the file is not of the correct radiometric type, whereas it will print out a series of constants if it is the correct type.

I may need to eventually add a check for file type problems as sometimes use of non-research grade IR cameras create non-radiometric jpgs, or the jpgs get altered by other programs that have been used to edit them.

If you are able to share a sample image taken from your camera here (or emailed if data sensitive), I can more effectively check.  But if the import function is working, then it suggests you have installed most things properly.  I can better assist if I have a sample image.

**Comment by gtatters** [comment] 2020-02-21 17:01
or, one simple suggestion is to rename your file to .jpg, not .jpeg.  Without checking my code it is possible that I assume users are using .jpg file extensions.  It is not something I check for.

**Comment by RomyWichmann** [comment] 2020-02-21 17:12
Ran the tool and don't get an error  - it is extracting the values. I've tried to convert but it is not helping. 
here is a sample file:
![FLIR1000003](https://user-images.githubusercontent.com/61289762/75055642-43ec4880-548a-11ea-82e1-82db9e6428fd.jpeg)

**Comment by RomyWichmann** [comment] 2020-02-21 17:12
i can also take one without the numbers and writing. If that would be better

**Comment by gtatters** [comment] 2020-02-21 18:29
oh no, not one of those MSX fusion images.  I don't like those. Usually I can extract the thermal data from them, but they are inconsistent.  I think that is messing up the convert function since inside the flir file are multiple jpg headers and exiftool and my functions can't translate them all efficiently.  

Any chance you can turn that feature off and take new images?

**Comment by gtatters** [comment] 2020-02-21 21:50
I've tried opening that file up in FLIR's programs and it does not open up as a radiometric image.  Despite the appearance of being a radiometric file, FLIR's program thinks it is a simple RGB JPG as well, so I'm not likely to solve a problem generated by their software.  This might truly be a problem with the hybrid images.  I get the same error with importing your image into ThermimageJ and it is based on the quality of the camera and the firewalled capabilities that the camera is limited to saving, unless you can find a way to turn the fusion part off, or change a save setting.

**Comment by gtatters** [comment] 2020-02-22 17:44
for future reference try in the terminal window:

```
exiftool -*RawThermalImageType* yourfilename.JPG
```

If you should obtain either:

> Raw Thermal Image Type          : TIFF

or

> Raw Thermal Image Type          : PNG

If you get nothing as a result, it is likely you do not have a radiometric jpg.

**Closed as completed** 2020-02-22 17:49 UTC
Labels: bug, invalid file type

**Comment by RomyWichmann** [comment] 2020-02-27 19:46
Hey, just wanted to let you know that we have exchanged the camera and everything is working now! I can import all images and analyse them. thanks again so much for your help with this!!

**Comment by gtatters** [comment] 2020-02-27 20:49
Thanks for the feedback and update!  Sorry for the trouble with the camera, but I'm glad the new files import better.  This is good news for me.

**Comment by shojajm** [comment] 2020-12-23 01:13
Hi there. I am currently trying to use your ThermImageJ plugin to import a thermal image and have been recieving this error -- -- 

"Warning -- Raw Thermal Type Unknown. This file might not be a radiometric JPG.
Setting Raw Thermal Type to tiff and attempting conversion. If resulting file is 0 bytes, the jpg cannot be converted.
Examine the settings on your camera to ensure radiometric jpgs are being saved.
Raw Thermal Type:  tiff
Converting 02 C1.jpg to 02C1.tif

FLIR JPG files converted into tiff format.  Import these and convert to temperature using the Raw2Temp macro.

Use the File->Import->Image Sequence function to load in images
Some images may require that the pixel byte order be swapped.  Use the Byte Swapper plugin after importing if necessaary
Done"

How can I check to see if the image is a radiometric JPG and furthermore if it is what is causing the issue? 
Thank you.

**Comment by gtatters** [comment] 2021-05-05 22:15
at the terminal window type:

`exiftool -*RawThermalImageType* yourfilename.JPG`

If you should obtain either:

Raw Thermal Image Type : TIFF

or

Raw Thermal Image Type : PNG

If you get nothing as a result, it is likely you do not have a radiometric jpg.

If you can't import, chances are your camera is not capable of taking a radiometric jpg or you have to examine the camera software settings.  This package of macros assumes you have a camera capable of research grade radiometric jpgs.
